font_family      IosevkaTermSlab NFM
bold_font        IosevkaTermSlab NFM Bold
italic_font      IosevkaTermSlab NFM Italic
bold_italic_font IosevkaTermSlab NFM Bold Italic

font_size 14

adjust_line_height 1
disable_ligatures never

font_features none

cursor #C55428
cursor_text_color #121122

cursor_shape block
cursor_blink_interval -1
cursor_stop_blinking_after 15.0

foreground #808080
background #121122
background_opacity 1.0

window_padding_width 0.0

#: black
color0 #505050
color8 #808080

#: red
color1 #7B4579
color9 #80BAB4

#: green
color2 #705681
color10 #C0A3D5

#: yellow
color3 #5B5681
color11 #C9C7FD

#: blue
color4 #3E5A80
color12 #90C5E8

#: magenta
color5 #7B2F5E
color13 #D2FFE6

#: cyan
color6 #A61B1D
color14 #EBDE95

#: white
color7 #C55428
color15 #F3FFE4
